# hash:sha256:5beb09525f77002c925ed76b72f7006a6a29446696497a843903a5d511e73ab8
FROM registry.codeocean.com/codeocean/miniconda3:4.9.2-python3.8-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys \
        0xAD2323F17326AE31401037733E05EBFF05441C52 \
        E298A3A825C0D65DFD57CBB651716619E084DAB9 \
    && apt-get update \
    && apt-get install -y --no-install-recommends software-properties-common \
    && add-apt-repository -y 'deb http://deb.codeocean.com/rstudio-server-bionic/ ubuntu main' \
    && add-apt-repository -y 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/' \
    && apt-get purge -y --autoremove software-properties-common \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        default-jdk \
        dirmngr \
        libc6 \
        libcairo2-dev \
        libcurl4-gnutls-dev \
        libgit2-dev \
        libssl-dev \
        libxml2-dev \
        libxt-dev \
        pkg-config \
        r-base \
        r-base-core \
        r-recommended \
        software-properties-common \
    && rm -rf /var/lib/apt/lists/*

RUN conda install -y --channel=defaults --channel=bioconda --channel=conda-forge \
        h5py==2.10.0 \
        nanopolish==0.11.1 \
        pillow==8.3.1 \
        pyyaml==5.4.1 \
        requests==2.26.0 \
        samtools==1.9 \
        scipy==1.7.1 \
        tensorflow==2.4.1 \
    && conda clean -ya

RUN echo 'options(repos = c(CRAN = "https://cloud.r-project.org/"), download.file.method = "libcurl")' >> $(Rscript -e 'cat(R.home())')/etc/Rprofile.site \
    && echo 'options(Ncpus = parallel::detectCores())' >> $(Rscript -e 'cat(R.home())')/etc/Rprofile.site \
    && Rscript -e 'options(warn=2); install.packages("remotes")'
RUN Rscript -e 'remotes::install_version("Matrix")' \
    && Rscript -e 'remotes::install_version("R.utils", "2.11.0")' \
    && Rscript -e 'remotes::install_version("Rcpp", "1.0.7")' \
    && Rscript -e 'remotes::install_version("abind", "1.4-5")' \
    && Rscript -e 'remotes::install_version("caret", "6.0-89")' \
    && Rscript -e 'remotes::install_version("data.table", "1.14.2")' \
    && Rscript -e 'remotes::install_version("doParallel", "1.0.16")' \
    && Rscript -e 'remotes::install_version("ff", "4.0.4")' \
    && Rscript -e 'remotes::install_version("foreach", "1.5.1")' \
    && Rscript -e 'remotes::install_version("keras", "2.6.1")' \
    && Rscript -e 'remotes::install_version("multiROC", "1.1.1")' \
    && Rscript -e 'remotes::install_version("optparse", "1.6.6")' \
    && Rscript -e 'remotes::install_version("pacman", "0.5.1")' \
    && Rscript -e 'remotes::install_version("plyr", "1.8.6")' \
    && Rscript -e 'remotes::install_version("pracma", "2.3.3")' \
    && Rscript -e 'remotes::install_version("scales", "1.1.1")' \
    && Rscript -e 'remotes::install_version("tensorflow", "2.6.0")' \
    && Rscript -e 'remotes::install_version("tidyverse", "1.3.1")' \
    && Rscript -e 'remotes::install_version("usefun", "0.4.8")' \
    && Rscript -e 'remotes::install_version("zoo", "1.8-9")'

COPY postInstall /
RUN /postInstall

COPY code /code/
